# Generated by Django 4.0.4 on 2022-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catitle', models.CharField(max_length=100, verbose_name='Title')),
                ('CaSubTitle', models.CharField(max_length=150, verbose_name='Subtitle')),
                ('CaImage', models.ImageField(upload_to='carouselImage', verbose_name='Image')),
                ('CaDesc', models.TextField(max_length=300, verbose_name='Description')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
