# Generated by Django 4.0.4 on 2022-06-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0003_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
